import { Job, FreelancerProfile } from '@/types';

// Mock jobs data for testing
export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Instructional Designer',
    company: 'TechLearn Inc.',
    location: 'New York, NY',
    locationType: 'hybrid',
    description:
      'We are seeking an experienced Instructional Designer to join our growing team. You will design engaging learning experiences for enterprise clients using modern e-learning tools and methodologies. Experience with ADDIE, SAM, and agile development methodologies required.',
    requirements: [
      '5+ years of instructional design experience',
      'Expertise in Articulate Storyline and Rise',
      'Strong understanding of adult learning principles',
      'Experience with LMS administration',
    ],
    salary: { min: 85000, max: 110000, currency: 'USD', period: 'annual' },
    category: 'instructional-design',
    experienceLevel: 'senior',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/1',
    sourceSite: 'LinkedIn',
    postedAt: new Date('2024-12-05'),
    expiresAt: new Date('2025-01-05'),
    isFeatured: true,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '2',
    title: 'E-Learning Developer',
    company: 'Global Training Solutions',
    location: 'Remote',
    locationType: 'remote',
    description:
      'Join our creative team as an E-Learning Developer. You will build interactive courses using Articulate 360, Adobe Captivate, and custom HTML5 solutions. Strong visual design skills and attention to detail required.',
    requirements: [
      '3+ years of e-learning development',
      'Proficiency in Articulate 360 suite',
      'HTML5, CSS, JavaScript skills',
      'Video editing experience a plus',
    ],
    salary: { min: 70000, max: 90000, currency: 'USD', period: 'annual' },
    category: 'elearning-development',
    experienceLevel: 'mid',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/2',
    sourceSite: 'Indeed',
    postedAt: new Date('2024-12-07'),
    expiresAt: new Date('2025-01-07'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '3',
    title: 'Learning Experience Designer',
    company: 'EdTech Innovators',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    description:
      'Design cutting-edge learning experiences for our SaaS platform. Work closely with product and engineering teams to create engaging, effective training content that scales.',
    requirements: [
      '4+ years in learning design or UX',
      'Experience with design thinking',
      'Data-driven approach to learning',
      'Strong portfolio required',
    ],
    salary: { min: 95000, max: 125000, currency: 'USD', period: 'annual' },
    category: 'instructional-design',
    experienceLevel: 'senior',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/3',
    sourceSite: 'Glassdoor',
    postedAt: new Date('2024-12-06'),
    expiresAt: new Date('2025-01-06'),
    isFeatured: true,
    isDirectPost: true,
    status: 'active',
  },
  {
    id: '4',
    title: 'Corporate Training Manager',
    company: 'Fortune 500 Company',
    location: 'Chicago, IL',
    locationType: 'onsite',
    description:
      'Lead our corporate training initiatives across multiple departments. Manage a team of trainers and oversee the development and delivery of training programs.',
    requirements: [
      '7+ years in corporate training',
      'Management experience required',
      'Budget management skills',
      'Change management certification preferred',
    ],
    salary: { min: 100000, max: 140000, currency: 'USD', period: 'annual' },
    category: 'corporate-training',
    experienceLevel: 'lead',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/4',
    sourceSite: 'LinkedIn',
    postedAt: new Date('2024-12-04'),
    expiresAt: new Date('2025-01-04'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '5',
    title: 'Freelance Articulate Developer',
    company: 'Creative Learning Agency',
    location: 'Remote',
    locationType: 'remote',
    description:
      'Contract opportunity for an experienced Articulate developer. Project-based work creating interactive courses for various clients in healthcare and finance.',
    requirements: [
      '3+ years with Articulate Storyline',
      'Strong visual design skills',
      'Ability to meet deadlines',
      'Portfolio of completed projects',
    ],
    salary: { min: 50, max: 75, currency: 'USD', period: 'hourly' },
    category: 'elearning-development',
    experienceLevel: 'mid',
    employmentType: 'freelance',
    sourceUrl: 'https://example.com/job/5',
    sourceSite: 'eLearning Industry',
    postedAt: new Date('2024-12-08'),
    expiresAt: new Date('2025-01-08'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '6',
    title: 'LMS Administrator',
    company: 'Healthcare Systems Inc.',
    location: 'Boston, MA',
    locationType: 'hybrid',
    description:
      'Manage and optimize our learning management system. Handle user administration, reporting, content uploads, and troubleshooting.',
    requirements: [
      '2+ years LMS administration',
      'Experience with Cornerstone or similar',
      'SQL skills for reporting',
      'Healthcare industry experience preferred',
    ],
    salary: { min: 60000, max: 75000, currency: 'USD', period: 'annual' },
    category: 'learning-management',
    experienceLevel: 'mid',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/6',
    sourceSite: 'Indeed',
    postedAt: new Date('2024-12-03'),
    expiresAt: new Date('2025-01-03'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '7',
    title: 'Junior Instructional Designer',
    company: 'StartUp Academy',
    location: 'Austin, TX',
    locationType: 'remote',
    description:
      'Great opportunity for someone starting their ID career. Work with senior designers on real projects and develop your skills in a supportive environment.',
    requirements: [
      '0-2 years experience',
      'Degree in ID, Education, or related field',
      'Eager to learn new tools',
      'Strong writing skills',
    ],
    salary: { min: 50000, max: 60000, currency: 'USD', period: 'annual' },
    category: 'instructional-design',
    experienceLevel: 'entry',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/7',
    sourceSite: 'LinkedIn',
    postedAt: new Date('2024-12-08'),
    expiresAt: new Date('2025-01-08'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
  {
    id: '8',
    title: 'Training Facilitator',
    company: 'Professional Services Firm',
    location: 'Denver, CO',
    locationType: 'onsite',
    description:
      'Deliver engaging training sessions for our consulting practice. Both virtual and in-person facilitation required.',
    requirements: [
      '3+ years facilitation experience',
      'Comfortable with large groups',
      'Virtual facilitation skills',
      'Travel up to 25%',
    ],
    salary: { min: 65000, max: 80000, currency: 'USD', period: 'annual' },
    category: 'training-facilitation',
    experienceLevel: 'mid',
    employmentType: 'full-time',
    sourceUrl: 'https://example.com/job/8',
    sourceSite: 'Glassdoor',
    postedAt: new Date('2024-12-07'),
    expiresAt: new Date('2025-01-07'),
    isFeatured: false,
    isDirectPost: false,
    status: 'active',
  },
];

// Mock freelancer profiles for testing
export const mockFreelancers: FreelancerProfile[] = [
  {
    id: '1',
    userId: 'user1',
    displayName: 'Sarah Chen',
    headline: 'Senior Instructional Designer | Articulate Expert | 10+ Years Experience',
    bio: 'I help organizations create engaging, effective learning experiences. Specializing in corporate training, compliance, and onboarding programs. Certified in ADDIE and SAM methodologies.',
    avatarUrl: undefined,
    location: 'Seattle, WA',
    timezone: 'America/Los_Angeles',
    availableRemotely: true,
    specializations: ['instructional-design', 'elearning-development', 'corporate-training'],
    skills: [
      'Articulate Storyline',
      'Articulate Rise',
      'Adobe Captivate',
      'Camtasia',
      'ADDIE',
      'SAM',
      'xAPI',
      'SCORM',
    ],
    experienceYears: 10,
    hourlyRate: { min: 85, max: 125, currency: 'USD' },
    portfolioUrl: 'https://sarahchen.design',
    linkedinUrl: 'https://linkedin.com/in/sarahchen',
    websiteUrl: undefined,
    availability: 'available',
    availabilityNote: 'Taking on new projects starting January',
    isFeatured: true,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
    status: 'active',
  },
  {
    id: '2',
    userId: 'user2',
    displayName: 'Marcus Johnson',
    headline: 'E-Learning Developer | Motion Graphics | Interactive Video',
    bio: 'Creative e-learning developer with a background in video production. I bring stories to life through interactive video, animations, and immersive learning experiences.',
    avatarUrl: undefined,
    location: 'Los Angeles, CA',
    timezone: 'America/Los_Angeles',
    availableRemotely: true,
    specializations: ['elearning-development', 'learning-technology'],
    skills: [
      'After Effects',
      'Premiere Pro',
      'Articulate Storyline',
      'Vyond',
      'HTML5',
      'JavaScript',
      'Video Production',
    ],
    experienceYears: 6,
    hourlyRate: { min: 75, max: 100, currency: 'USD' },
    portfolioUrl: 'https://marcusjohnson.dev',
    linkedinUrl: 'https://linkedin.com/in/marcusjohnson',
    websiteUrl: 'https://mjcreative.co',
    availability: 'limited',
    availabilityNote: 'Currently on a project, available for small tasks',
    isFeatured: false,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-15'),
    status: 'active',
  },
  {
    id: '3',
    userId: 'user3',
    displayName: 'Emily Rodriguez',
    headline: 'Learning Consultant | Needs Analysis | Program Design',
    bio: 'Strategic learning consultant helping organizations identify training needs and design comprehensive learning programs. Former CLO with Fortune 500 experience.',
    avatarUrl: undefined,
    location: 'New York, NY',
    timezone: 'America/New_York',
    availableRemotely: true,
    specializations: ['talent-development', 'curriculum-development', 'corporate-training'],
    skills: [
      'Needs Analysis',
      'Program Design',
      'Stakeholder Management',
      'ROI Measurement',
      'Change Management',
      'Executive Coaching',
    ],
    experienceYears: 15,
    hourlyRate: { min: 150, max: 250, currency: 'USD' },
    portfolioUrl: undefined,
    linkedinUrl: 'https://linkedin.com/in/emilyrodriguez',
    websiteUrl: 'https://rodriguezlearning.com',
    availability: 'available',
    isFeatured: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-12-05'),
    status: 'active',
  },
  {
    id: '4',
    userId: 'user4',
    displayName: 'David Kim',
    headline: 'Technical Trainer | Software Training | Documentation',
    bio: 'Specialized in creating technical training for software products. Strong background in software development makes me uniquely qualified to train technical audiences.',
    avatarUrl: undefined,
    location: 'San Jose, CA',
    timezone: 'America/Los_Angeles',
    availableRemotely: true,
    specializations: ['training-facilitation', 'curriculum-development'],
    skills: [
      'Technical Writing',
      'Software Training',
      'API Documentation',
      'Confluence',
      'Python',
      'SQL',
      'Virtual Facilitation',
    ],
    experienceYears: 8,
    hourlyRate: { min: 90, max: 130, currency: 'USD' },
    portfolioUrl: undefined,
    linkedinUrl: 'https://linkedin.com/in/davidkim',
    websiteUrl: undefined,
    availability: 'available',
    isFeatured: false,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-11-20'),
    status: 'active',
  },
  {
    id: '5',
    userId: 'user5',
    displayName: 'Amanda Foster',
    headline: 'Compliance Training Specialist | Healthcare & Finance',
    bio: 'Expert in regulated industries compliance training. Deep experience in healthcare (HIPAA) and financial services (SOX, AML). Making compliance training actually engaging.',
    avatarUrl: undefined,
    location: 'Chicago, IL',
    timezone: 'America/Chicago',
    availableRemotely: true,
    specializations: ['instructional-design', 'corporate-training'],
    skills: [
      'Compliance Training',
      'HIPAA',
      'Healthcare Training',
      'Financial Services',
      'Articulate Rise',
      'Lectora',
      'Accessibility (508)',
    ],
    experienceYears: 12,
    hourlyRate: { min: 100, max: 150, currency: 'USD' },
    portfolioUrl: 'https://amandafoster.training',
    linkedinUrl: 'https://linkedin.com/in/amandafoster',
    websiteUrl: undefined,
    availability: 'limited',
    availabilityNote: 'Booking for Q2 2025',
    isFeatured: false,
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-12-08'),
    status: 'active',
  },
  {
    id: '6',
    userId: 'user6',
    displayName: 'James Wright',
    headline: 'LMS Consultant | Implementation & Migration Specialist',
    bio: 'Helping organizations select, implement, and optimize their learning management systems. Certified in multiple LMS platforms including Cornerstone, Workday Learning, and Docebo.',
    avatarUrl: undefined,
    location: 'Austin, TX',
    timezone: 'America/Chicago',
    availableRemotely: true,
    specializations: ['learning-management', 'learning-technology'],
    skills: [
      'LMS Implementation',
      'Cornerstone',
      'Workday Learning',
      'Docebo',
      'xAPI',
      'Data Migration',
      'Integration',
      'SCORM',
    ],
    experienceYears: 9,
    hourlyRate: { min: 120, max: 175, currency: 'USD' },
    portfolioUrl: undefined,
    linkedinUrl: 'https://linkedin.com/in/jameswright',
    websiteUrl: 'https://wrightlms.consulting',
    availability: 'available',
    isFeatured: true,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-12-01'),
    status: 'active',
  },
];
